Mugi/src/main/java/br/com/mugi/entity/Party.java
package br.com.mugi.entity;

import java.util.List;
import java.util.Objects;
import javax.persistence.*;

/**
 *
 * @author jose.bonifacio
 */
@Entity
@Table(name = "party")
public class Party implements PersistentEntity<Long> {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    @OneToMany(mappedBy = "party", cascade = CascadeType.REMOVE)
    private List<PartyMember> partyMembers;

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<PartyMember> getPartyMembers() {
        return partyMembers;
    }

    public void setPartyMembers(List<PartyMember> partyMembers) {
        this.partyMembers = partyMembers;
    }    
    
    @Override
    public boolean isNew() {
        return this.id == null;
    }    

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 11 * hash + Objects.hashCode(this.id);
        hash = 11 * hash + Objects.hashCode(this.name);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Party other = (Party) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        return true;
    }
    
    
    
}

Mugi/src/main/java/br/com/mugi/controller/list/AccountListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.repository.AccountRepository;
import br.com.mugi.util.CurrencyUtil;
import java.io.Serializable;
import java.math.BigDecimal;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author BONIFACIO
 */
@Named
@SessionScoped
public class AccountListController extends ListControllerImpl implements Serializable {

    @Inject
    private AccountRepository accountRepository;

    @Override
    public void loadItems() {
        setItems(accountRepository.getAllAsAccountListDTO(Session.getUser(),
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }    
    
    public String getValue(BigDecimal value, String locale) {
        return CurrencyUtil.getStringValue(value, locale);
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/EventListController.java
package br.com.mugi.controller.list;

import br.com.mugi.repository.EventRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class EventListController extends ListControllerImpl implements Serializable {
    
    @Inject
    private  EventRepository eventRepository;

    @Override
    public void loadItems() {
        setItems(eventRepository.getAllAsEventListDTO(getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

}

Mugi/src/main/java/br/com/mugi/controller/list/ListController.java
package br.com.mugi.controller.list;

import java.util.List;

/**
 *
 * @author jose.bonifacio
 */
public interface ListController<T> {
    
    public List getItems();
    public void clear();
    public void search();
    public void next();
    public void prev();
    public void first();
    public void last();
    public int getFirstPageResult();
    public int getLastPageResult();
    public int getTotalPages();
    public int getTotalRows();
    public void loadItems();
}

Mugi/src/main/java/br/com/mugi/controller/list/MemberListController.java
package br.com.mugi.controller.list;

import br.com.mugi.repository.MemberRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class MemberListController extends ListControllerImpl implements Serializable {

    @Inject
    private MemberRepository memberRepository;
    
    @Override
    public void loadItems() {
        setItems(memberRepository.getAllAsMemberListDTO(getSearch(), this.getPage(), this.getMaxResultsPerPage()));        
    }


}

Mugi/src/main/java/br/com/mugi/controller/list/PartyListController.java
package br.com.mugi.controller.list;

import br.com.mugi.repository.PartyRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class PartyListController extends ListControllerImpl implements Serializable {

    @Inject
    private PartyRepository partyRepository;

    @Override
    public void loadItems() {
        setItems(partyRepository.getAllAsPartyListDTO(getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/PartyMemberListController.java
package br.com.mugi.controller.list;

import br.com.mugi.entity.Party;
import br.com.mugi.repository.PartyMemberRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class PartyMemberListController extends ListControllerImpl implements Serializable {

    @Inject
    private PartyMemberRepository partyMemberRepository;

    private Party party;

    @Override
    public void loadItems() {
        setItems(partyMemberRepository.getByPartyAsPartyMemberListDTO(getParty(), getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

    public Party getParty() {
        if (party == null) {
            party = new Party();
        }
        return party;
    }

    public void setParty(Party party) {
        this.party = party;
    }
    
    public void newParty() {
        party = null;
        clear();
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/SourceListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.repository.SourceRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author BONIFACIO
 */
@Named
@SessionScoped
public class SourceListController extends ListControllerImpl implements Serializable {

    @Inject
    private SourceRepository sourceRepository;

    @Override
    public void loadItems() {
        setItems(sourceRepository.getAllAsSourceListDTO(Session.getUser(),
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionAccountHistoryListController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.entity.Account;
import br.com.mugi.repository.AccountRepository;
import br.com.mugi.repository.TransactionRepository;
import br.com.mugi.util.CurrencyUtil;
import br.com.mugi.util.DateUtil;
import java.io.Serializable;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Date;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionAccountHistoryListController extends ListControllerImpl implements Serializable {

    @Inject
    private TransactionRepository transactionRepository;
    @Inject
    private AccountRepository accountRepository;
    private Account account;

    @Override
    public void loadItems() {
        setItems(transactionRepository.getAllAsTransactionListDTO(Session.getUser(), account, null,
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }
    
    public String getDate(Date date, String pattern) {
        return DateUtil.getFormattedDate(date, pattern);
    }

    public String getValue(BigDecimal value, String locale) {
        return CurrencyUtil.getStringValue(value, locale);
    }
    
    public void loadAccount(Long id) {
        account = accountRepository.find(Account.class, id);
        search();
    }
    
    
    @Override
    public int getMaxResultsPerPage() {
        return 5;
    }
    
        @Override
    public int getFirstPageResult() {
        return (getMaxResultsPerPage() * (getPage() - 1)) + 1;
    }

    @Override
    public int getLastPageResult() {
        return getItems().size() + getMaxResultsPerPage() * (getPage() - 1);
    }

    @Override
    public int getTotalPages() {
        return new BigDecimal(getItems().getTotalRows()).divide(new BigDecimal(getMaxResultsPerPage()), RoundingMode.UP).intValue();
    }

    @Override
    public int getTotalRows() {
        return getItems().getTotalRows();
    }

}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionAllListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.repository.TransactionRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionAllListController extends ListControllerImpl implements Serializable {

    @Inject
    private TransactionRepository transactionRepository;

    @Override
    public void loadItems() {
        setItems(transactionRepository.getAllAsTransactionListDTO(Session.getUser(), null,
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionIncomeListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.enumerated.TransactionType;
import br.com.mugi.repository.TransactionRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionIncomeListController extends ListControllerImpl implements Serializable {

    @Inject
    private TransactionRepository transactionRepository;

    @Override
    public void loadItems() {
        setItems(transactionRepository.getAllAsTransactionListDTO(Session.getUser(), TransactionType.INCOME,
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionListController.java
package br.com.mugi.controller.list;

import br.com.mugi.util.CurrencyUtil;
import br.com.mugi.util.DateUtil;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionListController implements Serializable {

    @Inject
    private TransactionAllListController transactionAllListController;
    @Inject
    private TransactionIncomeListController transactionIncomeListController;
    @Inject
    private TransactionOutcomeListController transactionOutcomeListController;

    private String search = "";
    private int tab = 0;

    public String getSearch() {
        return search;
    }

    public void setSearch(String search) {
        this.search = search;
        transactionAllListController.setSearch(search);
        transactionIncomeListController.setSearch(search);
        transactionOutcomeListController.setSearch(search);
    }

    public int getTab() {
        return tab;
    }

    public void setTab(int tab) {
        this.tab = tab;
    }

    public void clear() {
        switch (tab) {
            case 0:
                transactionAllListController.clear();
                break;
            case 1:
                transactionIncomeListController.clear();
                break;
            case 2:
                transactionOutcomeListController.clear();
                break;
        }
    }
    
    public void search() {
        search(tab);
    }

    public void search(int tab) {
        this.tab = tab;
        switch (tab) {
            case 0:
                transactionAllListController.search();
                break;
            case 1:
                transactionIncomeListController.search();
                break;
            case 2:
                transactionOutcomeListController.search();
                break;
        }
    }

    public String getDate(Date date, String pattern) {
        return DateUtil.getFormattedDate(date, pattern);
    }

    public String getValue(BigDecimal value, String locale) {
        return CurrencyUtil.getStringValue(value, locale);
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionOutcomeListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.enumerated.TransactionType;
import br.com.mugi.repository.TransactionRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionOutcomeListController extends ListControllerImpl implements Serializable {

    @Inject
    private TransactionRepository transactionRepository;

    @Override
    public void loadItems() {
        setItems(transactionRepository.getAllAsTransactionListDTO(Session.getUser(), TransactionType.OUTCOME,
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/TransferListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.repository.TransferRepository;
import br.com.mugi.util.CurrencyUtil;
import br.com.mugi.util.DateUtil;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author BONIFACIO
 */
@Named
@SessionScoped
public class TransferListController extends ListControllerImpl implements Serializable {

    @Inject
    private TransferRepository transferRepository;

    @Override
    public void loadItems() {
        setItems(transferRepository.getAllAsTransferListDTO(Session.getUser(),
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

    public String getDate(Date date, String pattern) {
        return DateUtil.getFormattedDate(date, pattern);
    }

    public String getValue(BigDecimal value, String locale) {
        return CurrencyUtil.getStringValue(value, locale);
    }
}

Mugi/src/main/webapp/template/list/buttons.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:body>
        <ui:composition>
            <b:commandButton actionListener="#{listController.search()}" update="@form" value="" class="pull-right" icon="search" style="margin-bottom: 2px; height: 39px"/>    
            <h:inputText class="form-control pull-right" value="#{listController.search}" style="width: 30%; display: inline;"/>
        </ui:composition>
    </h:body>
</html>

Mugi/src/main/webapp/template/list/clickableRow.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:body>
        <ui:composition>
            <tr onclick="#{clickPath}" class="clickable">
                <ui:insert name="columns"/>     
                <td style="width: 5%; text-align: right;"><b:iconAwesome name="pencil"/></td> 
            </tr>
        </ui:composition>
    </h:body>
</html>

Mugi/src/main/webapp/template/list/footer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:body>
        <ui:composition>
            <hr/>
            <div class="text-center">
                <b:commandButton actionListener="#{listController.first()}" update="@form" disabled="#{listController.page == 1 or listController.page == null}" value="" style="cursor: default" iconAwesome="angle-double-left"/> 
                <b:commandButton actionListener="#{listController.prev()}" update="@form" disabled="#{listController.page == 1 or listController.page == null}" value="" style="cursor: default" iconAwesome="angle-left"/> 
                <b:button outcome="list" value="#{listController.page > listController.totalPages ? listController.totalPages : listController.page} - #{listController.totalPages}" disabled="true" style="cursor: default"></b:button>      
                <b:commandButton actionListener="#{listController.next()}" update="@form" disabled="#{listController.page == listController.totalPages or listController.totalPages == 0}" value=""  style="cursor: default" iconAwesome="angle-right" />
                <b:commandButton actionListener="#{listController.last()}" update="@form" disabled="#{listController.page == listController.totalPages or listController.totalPages == 0}" value=""  style="cursor: default" iconAwesome="angle-double-right" />
            </div>            
            <h6 class="text-center">
                <h:outputText value="#{listController.firstPageResult}-#{listController.lastPageResult} #{i18n['table.of']} #{listController.totalRows}"/>
            </h6>
        </ui:composition>
    </h:body>
</html>

Mugi/src/main/webapp/template/list/layout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:body> 
        <ui:composition template="../common/layout.xhtml">
            <ui:define name="sidebar">
                <ui:include src="../common/sidebar.xhtml" />
            </ui:define>
            <ui:define name="content" >                
                <h:form>
                    <h:panelGroup rendered="#{not dontRenderContextButtons}">
                        <b:button rendered="#{not customButtonsOnly}" outcome="form" value="#{i18n['actions.new']}" iconAwesome="plus" style="margin-bottom: 2px"></b:button>  
                        <ui:insert name="additionalButtons"/>
                        <ui:include src="buttons.xhtml"></ui:include>
                        <hr/>
                    </h:panelGroup>
                    <div id="workArea" class="workArea" >
                        <b:messages showSummary="false"/>
                        <ui:insert name="workArea"/>
                    </div>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Mugi/src/main/webapp/template/list/row.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:body>
        <ui:composition>
            <tr>
                <ui:insert name="columns">         
                </ui:insert>      
            </tr>
        </ui:composition>
    </h:body>
</html>

Mugi/src/main/webapp/template/list/table.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:body>
        <ui:composition>
            <ui:fragment rendered="#{includeButtons}">  
                <ui:include src="buttons.xhtml"></ui:include>
                <div class="form-group"/>
            </ui:fragment>
            <ui:fragment rendered="#{listController.totalRows == 0}">
                <b:well>
                    <h3 class="text-align-center">
                        <h:outputLabel value="#{i18n['table.noRecords']}"/>
                    </h3>
                </b:well>
            </ui:fragment>
            <ui:fragment rendered="#{listController.totalRows > 0}">
                <table class="table table-striped table-hover" style="margin-bottom: 0px;">
                    <thead>
                        <tr>                        
                            <ui:insert name="header">
                            </ui:insert>
                        </tr>
                    </thead>
                    <tbody>
                        <ui:insert name="rows">         
                        </ui:insert>     
                    </tbody>
                </table>
            </ui:fragment>
            <ui:fragment rendered="#{includeFooter and listController.totalRows > 0}">  
                <ui:include src="footer.xhtml"></ui:include>
            </ui:fragment>
        </ui:composition>
    </h:body>
</html>

Mugi/src/main/webapp/template/list/viewableRow.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:body>
        <ui:composition>
            <tr>
                <ui:insert name="columns"/>     
                <td style="text-align: right;">
                    <b:commandButton value="" actionListener="#{formBean.loadView(partyMember.id)}" oncomplete="#{clickPath}" ajax="true" update="#{update}" icon="zoom-in"/>
                </td> 
            </tr>
        </ui:composition>
    </h:body>
</html>