Mugi/src/main/java/br/com/mugi/dto/AccountListDTO.java
package br.com.mugi.dto;

import java.math.BigDecimal;

/**
 *
 * @author BONIFACIO
 */
public class AccountListDTO {

    private final Long id;
    private final String name;
    private final Long idUser;
    private final String nameUser;
    private final BigDecimal balance;

    public AccountListDTO(Long id, String name, Long idUser, String nameUser, BigDecimal balance) {
        this.id = id;
        this.name = name;
        this.idUser = idUser;
        this.nameUser = nameUser;
        this.balance = balance;
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public Long getIdUser() {
        return idUser;
    }

    public String getNameUser() {
        return nameUser;
    }
    
    public boolean getPositive() {
        if (balance == null) {
            return true;
        }
        return balance.signum() > -1 ;
    }

    public BigDecimal getBalance() {
        if (!getPositive()) {
            return balance.multiply(new BigDecimal(-1));
        }
        return balance;
    }

}

Mugi/src/main/java/br/com/mugi/entity/Party.java
package br.com.mugi.entity;

import java.util.List;
import java.util.Objects;
import javax.persistence.*;

/**
 *
 * @author jose.bonifacio
 */
@Entity
@Table(name = "party")
public class Party implements PersistentEntity<Long> {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    @OneToMany(mappedBy = "party", cascade = CascadeType.REMOVE)
    private List<PartyMember> partyMembers;

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<PartyMember> getPartyMembers() {
        return partyMembers;
    }

    public void setPartyMembers(List<PartyMember> partyMembers) {
        this.partyMembers = partyMembers;
    }    
    
    @Override
    public boolean isNew() {
        return this.id == null;
    }    

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 11 * hash + Objects.hashCode(this.id);
        hash = 11 * hash + Objects.hashCode(this.name);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Party other = (Party) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        return true;
    }
    
    
    
}

Mugi/src/main/java/br/com/mugi/entity/Source.java
package br.com.mugi.entity;

import br.com.mugi.enumerated.TransactionType;
import br.com.mugi.validator.Required;
import java.io.Serializable;
import java.util.Objects;
import javax.persistence.*;

/**
 *
 * @author jose.bonifacio
 */
@Entity
@Table(name = "source")
public class Source implements PersistentEntity<Long>, Serializable {

    public final static Long INITIAL_VALUE_ID = 1L;
    public final static Long TRANSFER_ID = 2L;
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Required
    @ManyToOne(fetch = FetchType.LAZY)
    private User user;
    @Required
    private String name;
    @Required
    @Enumerated(EnumType.STRING)
    private TransactionType type;

    public Source() {
    }

    public Source(Long id, Long idUser, String name) {
        this.id = id;
        this.user = new User();
        this.user.setId(idUser);
        this.name = name;
    }
    
    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public TransactionType getType() {
        return type;
    }

    public void setType(TransactionType type) {
        this.type = type;
    }
    
    public boolean isOpeningValue() {
        return INITIAL_VALUE_ID.equals(this.id);
    }    
    
    public boolean isTransfer() {
        return TRANSFER_ID.equals(this.id);
    }
    
    public boolean isDefault() {
        return isOpeningValue() || isTransfer();
    }

    @Override
    public boolean isNew() {
        return this.id == null;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 29 * hash + Objects.hashCode(this.name);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Source other = (Source) obj;
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        return true;
    }
    
}

Mugi/src/main/java/br/com/mugi/controller/list/AccountListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.repository.AccountRepository;
import br.com.mugi.util.CurrencyUtil;
import java.io.Serializable;
import java.math.BigDecimal;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author BONIFACIO
 */
@Named
@SessionScoped
public class AccountListController extends ListControllerImpl implements Serializable {

    @Inject
    private AccountRepository accountRepository;

    @Override
    public void loadItems() {
        setItems(accountRepository.getAllAsAccountListDTO(Session.getUser(),
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }    
    
    public String getValue(BigDecimal value, String locale) {
        return CurrencyUtil.getStringValue(value, locale);
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/EventListController.java
package br.com.mugi.controller.list;

import br.com.mugi.repository.EventRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class EventListController extends ListControllerImpl implements Serializable {
    
    @Inject
    private  EventRepository eventRepository;

    @Override
    public void loadItems() {
        setItems(eventRepository.getAllAsEventListDTO(getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

}

Mugi/src/main/java/br/com/mugi/controller/list/ListController.java
package br.com.mugi.controller.list;

import java.util.List;

/**
 *
 * @author jose.bonifacio
 */
public interface ListController<T> {
    
    public List getItems();
    public void clear();
    public void search();
    public void next();
    public void prev();
    public void first();
    public void last();
    public int getFirstPageResult();
    public int getLastPageResult();
    public int getTotalPages();
    public int getTotalRows();
    public void loadItems();
}

Mugi/src/main/java/br/com/mugi/controller/list/MemberListController.java
package br.com.mugi.controller.list;

import br.com.mugi.repository.MemberRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class MemberListController extends ListControllerImpl implements Serializable {

    @Inject
    private MemberRepository memberRepository;
    
    @Override
    public void loadItems() {
        setItems(memberRepository.getAllAsMemberListDTO(getSearch(), this.getPage(), this.getMaxResultsPerPage()));        
    }


}

Mugi/src/main/java/br/com/mugi/controller/list/PartyListController.java
package br.com.mugi.controller.list;

import br.com.mugi.repository.PartyRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class PartyListController extends ListControllerImpl implements Serializable {

    @Inject
    private PartyRepository partyRepository;

    @Override
    public void loadItems() {
        setItems(partyRepository.getAllAsPartyListDTO(getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/PartyMemberListController.java
package br.com.mugi.controller.list;

import br.com.mugi.entity.Party;
import br.com.mugi.repository.PartyMemberRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class PartyMemberListController extends ListControllerImpl implements Serializable {

    @Inject
    private PartyMemberRepository partyMemberRepository;

    private Party party;

    @Override
    public void loadItems() {
        setItems(partyMemberRepository.getByPartyAsPartyMemberListDTO(getParty(), getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

    public Party getParty() {
        if (party == null) {
            party = new Party();
        }
        return party;
    }

    public void setParty(Party party) {
        this.party = party;
    }
    
    public void newParty() {
        party = null;
        clear();
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/SourceListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.repository.SourceRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author BONIFACIO
 */
@Named
@SessionScoped
public class SourceListController extends ListControllerImpl implements Serializable {

    @Inject
    private SourceRepository sourceRepository;

    @Override
    public void loadItems() {
        setItems(sourceRepository.getAllAsSourceListDTO(Session.getUser(),
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionAccountHistoryListController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.entity.Account;
import br.com.mugi.repository.AccountRepository;
import br.com.mugi.repository.TransactionRepository;
import br.com.mugi.util.CurrencyUtil;
import br.com.mugi.util.DateUtil;
import java.io.Serializable;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Date;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionAccountHistoryListController extends ListControllerImpl implements Serializable {

    @Inject
    private TransactionRepository transactionRepository;
    @Inject
    private AccountRepository accountRepository;
    private Account account;

    @Override
    public void loadItems() {
        setItems(transactionRepository.getAllAsTransactionListDTO(Session.getUser(), account, null,
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }
    
    public String getDate(Date date, String pattern) {
        return DateUtil.getFormattedDate(date, pattern);
    }

    public String getValue(BigDecimal value, String locale) {
        return CurrencyUtil.getStringValue(value, locale);
    }
    
    public void loadAccount(Long id) {
        account = accountRepository.find(Account.class, id);
        search();
    }
    
    
    @Override
    public int getMaxResultsPerPage() {
        return 5;
    }
    
        @Override
    public int getFirstPageResult() {
        return (getMaxResultsPerPage() * (getPage() - 1)) + 1;
    }

    @Override
    public int getLastPageResult() {
        return getItems().size() + getMaxResultsPerPage() * (getPage() - 1);
    }

    @Override
    public int getTotalPages() {
        return new BigDecimal(getItems().getTotalRows()).divide(new BigDecimal(getMaxResultsPerPage()), RoundingMode.UP).intValue();
    }

    @Override
    public int getTotalRows() {
        return getItems().getTotalRows();
    }

}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionAllListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.repository.TransactionRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionAllListController extends ListControllerImpl implements Serializable {

    @Inject
    private TransactionRepository transactionRepository;

    @Override
    public void loadItems() {
        setItems(transactionRepository.getAllAsTransactionListDTO(Session.getUser(), null,
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionIncomeListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.enumerated.TransactionType;
import br.com.mugi.repository.TransactionRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionIncomeListController extends ListControllerImpl implements Serializable {

    @Inject
    private TransactionRepository transactionRepository;

    @Override
    public void loadItems() {
        setItems(transactionRepository.getAllAsTransactionListDTO(Session.getUser(), TransactionType.INCOME,
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionListController.java
package br.com.mugi.controller.list;

import br.com.mugi.util.CurrencyUtil;
import br.com.mugi.util.DateUtil;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionListController implements Serializable {

    @Inject
    private TransactionAllListController transactionAllListController;
    @Inject
    private TransactionIncomeListController transactionIncomeListController;
    @Inject
    private TransactionOutcomeListController transactionOutcomeListController;

    private String search = "";
    private int tab = 0;

    public String getSearch() {
        return search;
    }

    public void setSearch(String search) {
        this.search = search;
        transactionAllListController.setSearch(search);
        transactionIncomeListController.setSearch(search);
        transactionOutcomeListController.setSearch(search);
    }

    public int getTab() {
        return tab;
    }

    public void setTab(int tab) {
        this.tab = tab;
    }

    public void clear() {
        switch (tab) {
            case 0:
                transactionAllListController.clear();
                break;
            case 1:
                transactionIncomeListController.clear();
                break;
            case 2:
                transactionOutcomeListController.clear();
                break;
        }
    }
    
    public void search() {
        search(tab);
    }

    public void search(int tab) {
        this.tab = tab;
        switch (tab) {
            case 0:
                transactionAllListController.search();
                break;
            case 1:
                transactionIncomeListController.search();
                break;
            case 2:
                transactionOutcomeListController.search();
                break;
        }
    }

    public String getDate(Date date, String pattern) {
        return DateUtil.getFormattedDate(date, pattern);
    }

    public String getValue(BigDecimal value, String locale) {
        return CurrencyUtil.getStringValue(value, locale);
    }
}

Mugi/src/main/webapp/secured/account/form.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:body>
        <ui:composition template="/template/form/layout.xhtml">

            <f:metadata>
                <f:viewParam name="id" value="#{accountFormController.account.id}" />
                <f:viewAction if="#{not empty param['id']}" action="#{accountFormController.loadAccount(accountFormController.account.id)}" />
            </f:metadata>

            <ui:param name="formBean" value="#{accountFormController}"/>
            <ui:param name="context" value="#{i18n['account.context.form']}" />
            <ui:param name="includeDelete" value="true"/>
            <ui:param name="deleteContext" value="#{i18n['account.delete.context']}"/>
            <ui:param name="entityName" value="#{accountFormController.account.name}"/>
            <ui:param name="entity" value="#{accountFormController.account}"/>
            <ui:param name="backToList" value="#{request.contextPath}/accounts"/>

            <ui:define name="workArea" >
                <h:panelGroup >
                    <ui:decorate template="#{input}">
                        <ui:param name="label" value="#{i18n['account.input.name']}"/><ui:param name="for" value="account"/>
                        <ui:define name="field">
                            <b:inputText id="account" value="#{accountFormController.account.name}">
                                <f:validator validatorId="requiredValidator"/>
                            </b:inputText>
                        </ui:define>
                    </ui:decorate> 

                    <ui:fragment rendered="#{accountFormController.account.new}">
                        <ui:decorate template="#{input}">
                            <ui:param name="label" value="#{i18n['account.input.initialValue']}"/><ui:param name="for" value="value"/>
                            <ui:define name="field">  
                                <b:inputText id="value" value="#{accountFormController.account.openingValue}" converterMessage="#{i18n[settingsController.currency.invalidMessage]}" >
                                    <f:facet name="prepend">
                                        <h:outputText value="#{settingsController.currency.symbol}" />
                                    </f:facet>
                                    <f:convertNumber locale="#{settingsController.currency.locale}" maxFractionDigits="2" minFractionDigits="2" />
                                </b:inputText>
                            </ui:define>
                        </ui:decorate> 
                    </ui:fragment>

                    <ui:decorate template="#{input}">
                        <ui:param name="label" value="#{i18n['transaction.input.date']}"/><ui:param name="for" value="date"/>
                        <ui:define name="field">
                            <b:datepicker id="date" value="#{accountFormController.account.openingDate}" mode="icon-popup" />
                        </ui:define>
                    </ui:decorate>     

                    <b:column>
                        <b:slider mode="edit" value="#{accountFormController.hours}" label="#{i18n['calendar.hours']}" min="0" max="23"  />
                    </b:column>

                    <b:column>
                        <b:slider mode="edit"  value="#{accountFormController.minutes}" label="#{i18n['calendar.minutes']}" min="0" max="59" />
                    </b:column>

                </h:panelGroup>  
            </ui:define>     
        </ui:composition>
    </h:body>
</html>

Mugi/src/main/webapp/secured/account/list.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:body>
        <ui:composition template="/template/list/layout.xhtml">
            <f:metadata>
                <f:viewAction action="#{accountListController.clear()}" />
            </f:metadata>

            <ui:param name="listController" value="#{accountListController}" />
            <ui:param name="context" value="#{i18n['account.context.list']}" />
            <ui:param value="#{accountListController.page}" name="page"/>
            <ui:param name="includeFooter" value="true"/>

            <ui:define name="workArea" >
                <ui:decorate template="/template/list/table.xhtml">
                    <ui:define name="header">
                        <td style="width: 5%; text-align: right;"></td>
                        <td style="width: 50%;"><h:outputLabel value="#{i18n['account.list.name']}" /> </td>
                        <td style="width: 40%; text-align: right;"><h:outputLabel value="#{i18n['account.list.balance']} (#{settingsController.currency.symbol})" /> </td>
                    </ui:define>
                    <ui:define name="rows">
                        <ui:repeat value="#{accountListController.items}" var="event" >
                            <ui:param value="#{event}" name="item"/>
                            <ui:param name="clickPath" value="document.location.href = '../account/#{item.id}'"/>
                            <ui:decorate template="/template/list/clickableRow.xhtml" >
                                <ui:define name="columns">
                                    <td style="width: 5%;"><b:commandButton value="#{i18n['account.list.history']}" size="xs" onclick="stopPropagation(event); BsF.ajax.callAjax(this, event,'transactionHistory transactionHistoryForm','j_idt53',function(){$('.transactionHistoryModal').modal(); return false;});;;return false;" actionListener="#{transactionAccountHistoryListController.loadAccount(item.id)}" ajax="true" update=":transactionHistory :transactionHistoryForm" iconAwesome="search-plus"/></td>
                                    <td style="width: 50%;">#{item.name}</td>
                                    <td style="width: 40%; text-align: right; font-weight: bold" class="#{item.positive ? 'font-green' : 'font-red'}"><b:iconAwesome name="#{item.positive ? 'plus' : 'minus'}" class="#{item.positive ? 'font-green' : 'font-red'}" />  #{accountListController.getValue(item.balance, settingsController.currency.locale)}</td>
                                </ui:define>
                            </ui:decorate>
                        </ui:repeat> 
                    </ui:define>
                </ui:decorate>   
            </ui:define>
            <ui:define name="additionalModal">
                <ui:param name="listController" value="#{transactionAccountHistoryListController}" />
                <ui:param value="#{transactionAccountHistoryListController.page}" name="page"/>
                <ui:param name="includeFooter" value="true"/>
                <ui:include src="transactionHistory.xhtml" /> 
            </ui:define>    
        </ui:composition>
    </h:body>
</html>

Mugi/src/main/webapp/secured/account/transactionHistory.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:body>
        <ui:composition> 
            <b:modal id="transactionHistory" title="#{transactionAccountHistoryListController.account.name}" styleClass="transactionHistoryModal">
                <h:form id="transactionHistoryForm">
                    <ui:decorate template="/template/list/table.xhtml">
                        <ui:define name="header">
                            <td style="width: 20%;" class="visible-sm visible-md visible-lg"><h:outputLabel value="#{i18n['transaction.list.account']}" /> </td>
                            <td style="width: 20%;" class="visible-sm visible-md visible-lg"><h:outputLabel value="#{i18n['transaction.list.source']}" /> </td>
                            <td style="width: 10%; text-align: center;"><h:outputLabel value="#{i18n['transaction.list.completed']}" /> </td>
                            <td style="width: 15%; text-align: center;"><h:outputLabel value="#{i18n['transaction.list.date']}" /> </td>
                            <td style="width: 35%; text-align: right;"><h:outputLabel value="#{i18n['transaction.list.value']} (#{settingsController.currency.symbol})" /> </td>
                        </ui:define>
                        <ui:define name="rows">
                            <ui:repeat value="#{listController.items}" var="event" >
                                <ui:param value="#{event}" name="item"/>
                                <ui:decorate template="/template/list/row.xhtml" >
                                    <ui:define name="columns">
                                        <td style="width: 20%;" class="visible-sm visible-md visible-lg">#{item.nameAccount}</td>
                                        <td style="width: 20%;" class="visible-sm visible-md visible-lg">#{item.defaultValue ? i18n[item.nameSource] : item.nameSource}</td>
                                        <td style="width: 10%; text-align: center;"><b:iconAwesome name="#{item.deferred ? 'check' : 'remove'}"/></td>
                                        <td style="width: 15%; text-align: center;">#{transactionAccountHistoryListController.getDate(item.date, i18n['transaction.list.dateMask'])}</td>
                                        <td style="width: 35%; text-align: right; font-weight: bold" class="#{item.income ? 'font-green' : 'font-red'}"><b:iconAwesome name="#{item.income ? 'plus' : 'minus'}" class="#{item.income ? 'font-green' : 'font-red'}" />  #{transactionAccountHistoryListController.getValue(item.value, settingsController.currency.locale)}</td>
                                    </ui:define>
                                </ui:decorate>
                            </ui:repeat> 
                        </ui:define>
                    </ui:decorate>  
                </h:form>
            </b:modal>
        </ui:composition> 
    </h:body>
</html>