Mugi/src/main/java/br/com/mugi/entity/Party.java
package br.com.mugi.entity;

import java.util.List;
import java.util.Objects;
import javax.persistence.*;

/**
 *
 * @author jose.bonifacio
 */
@Entity
@Table(name = "party")
public class Party implements PersistentEntity<Long> {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    @OneToMany(mappedBy = "party", cascade = CascadeType.REMOVE)
    private List<PartyMember> partyMembers;

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<PartyMember> getPartyMembers() {
        return partyMembers;
    }

    public void setPartyMembers(List<PartyMember> partyMembers) {
        this.partyMembers = partyMembers;
    }    
    
    @Override
    public boolean isNew() {
        return this.id == null;
    }    

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 11 * hash + Objects.hashCode(this.id);
        hash = 11 * hash + Objects.hashCode(this.name);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Party other = (Party) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        return true;
    }
    
    
    
}

Mugi/src/main/java/br/com/mugi/controller/list/AccountListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.repository.AccountRepository;
import br.com.mugi.util.CurrencyUtil;
import java.io.Serializable;
import java.math.BigDecimal;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author BONIFACIO
 */
@Named
@SessionScoped
public class AccountListController extends ListControllerImpl implements Serializable {

    @Inject
    private AccountRepository accountRepository;

    @Override
    public void loadItems() {
        setItems(accountRepository.getAllAsAccountListDTO(Session.getUser(),
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }    
    
    public String getValue(BigDecimal value, String locale) {
        return CurrencyUtil.getStringValue(value, locale);
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/EventListController.java
package br.com.mugi.controller.list;

import br.com.mugi.repository.EventRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class EventListController extends ListControllerImpl implements Serializable {
    
    @Inject
    private  EventRepository eventRepository;

    @Override
    public void loadItems() {
        setItems(eventRepository.getAllAsEventListDTO(getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

}

Mugi/src/main/java/br/com/mugi/controller/list/ListController.java
package br.com.mugi.controller.list;

import java.util.List;

/**
 *
 * @author jose.bonifacio
 */
public interface ListController<T> {
    
    public List getItems();
    public void clear();
    public void search();
    public void next();
    public void prev();
    public void first();
    public void last();
    public int getFirstPageResult();
    public int getLastPageResult();
    public int getTotalPages();
    public int getTotalRows();
    public void loadItems();
}

Mugi/src/main/java/br/com/mugi/controller/list/MemberListController.java
package br.com.mugi.controller.list;

import br.com.mugi.repository.MemberRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class MemberListController extends ListControllerImpl implements Serializable {

    @Inject
    private MemberRepository memberRepository;
    
    @Override
    public void loadItems() {
        setItems(memberRepository.getAllAsMemberListDTO(getSearch(), this.getPage(), this.getMaxResultsPerPage()));        
    }


}

Mugi/src/main/java/br/com/mugi/controller/list/PartyListController.java
package br.com.mugi.controller.list;

import br.com.mugi.repository.PartyRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class PartyListController extends ListControllerImpl implements Serializable {

    @Inject
    private PartyRepository partyRepository;

    @Override
    public void loadItems() {
        setItems(partyRepository.getAllAsPartyListDTO(getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/PartyMemberListController.java
package br.com.mugi.controller.list;

import br.com.mugi.entity.Party;
import br.com.mugi.repository.PartyMemberRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class PartyMemberListController extends ListControllerImpl implements Serializable {

    @Inject
    private PartyMemberRepository partyMemberRepository;

    private Party party;

    @Override
    public void loadItems() {
        setItems(partyMemberRepository.getByPartyAsPartyMemberListDTO(getParty(), getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

    public Party getParty() {
        if (party == null) {
            party = new Party();
        }
        return party;
    }

    public void setParty(Party party) {
        this.party = party;
    }
    
    public void newParty() {
        party = null;
        clear();
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/SourceListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.repository.SourceRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author BONIFACIO
 */
@Named
@SessionScoped
public class SourceListController extends ListControllerImpl implements Serializable {

    @Inject
    private SourceRepository sourceRepository;

    @Override
    public void loadItems() {
        setItems(sourceRepository.getAllAsSourceListDTO(Session.getUser(),
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionAccountHistoryListController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.entity.Account;
import br.com.mugi.repository.AccountRepository;
import br.com.mugi.repository.TransactionRepository;
import br.com.mugi.util.CurrencyUtil;
import br.com.mugi.util.DateUtil;
import java.io.Serializable;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Date;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionAccountHistoryListController extends ListControllerImpl implements Serializable {

    @Inject
    private TransactionRepository transactionRepository;
    @Inject
    private AccountRepository accountRepository;
    private Account account;

    @Override
    public void loadItems() {
        setItems(transactionRepository.getAllAsTransactionListDTO(Session.getUser(), account, null,
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }
    
    public String getDate(Date date, String pattern) {
        return DateUtil.getFormattedDate(date, pattern);
    }

    public String getValue(BigDecimal value, String locale) {
        return CurrencyUtil.getStringValue(value, locale);
    }
    
    public void loadAccount(Long id) {
        account = accountRepository.find(Account.class, id);
        search();
    }
    
    
    @Override
    public int getMaxResultsPerPage() {
        return 5;
    }
    
        @Override
    public int getFirstPageResult() {
        return (getMaxResultsPerPage() * (getPage() - 1)) + 1;
    }

    @Override
    public int getLastPageResult() {
        return getItems().size() + getMaxResultsPerPage() * (getPage() - 1);
    }

    @Override
    public int getTotalPages() {
        return new BigDecimal(getItems().getTotalRows()).divide(new BigDecimal(getMaxResultsPerPage()), RoundingMode.UP).intValue();
    }

    @Override
    public int getTotalRows() {
        return getItems().getTotalRows();
    }

}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionAllListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.repository.TransactionRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionAllListController extends ListControllerImpl implements Serializable {

    @Inject
    private TransactionRepository transactionRepository;

    @Override
    public void loadItems() {
        setItems(transactionRepository.getAllAsTransactionListDTO(Session.getUser(), null,
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionIncomeListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.enumerated.TransactionType;
import br.com.mugi.repository.TransactionRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionIncomeListController extends ListControllerImpl implements Serializable {

    @Inject
    private TransactionRepository transactionRepository;

    @Override
    public void loadItems() {
        setItems(transactionRepository.getAllAsTransactionListDTO(Session.getUser(), TransactionType.INCOME,
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionListController.java
package br.com.mugi.controller.list;

import br.com.mugi.util.CurrencyUtil;
import br.com.mugi.util.DateUtil;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionListController implements Serializable {

    @Inject
    private TransactionAllListController transactionAllListController;
    @Inject
    private TransactionIncomeListController transactionIncomeListController;
    @Inject
    private TransactionOutcomeListController transactionOutcomeListController;

    private String search = "";
    private int tab = 0;

    public String getSearch() {
        return search;
    }

    public void setSearch(String search) {
        this.search = search;
        transactionAllListController.setSearch(search);
        transactionIncomeListController.setSearch(search);
        transactionOutcomeListController.setSearch(search);
    }

    public int getTab() {
        return tab;
    }

    public void setTab(int tab) {
        this.tab = tab;
    }

    public void clear() {
        switch (tab) {
            case 0:
                transactionAllListController.clear();
                break;
            case 1:
                transactionIncomeListController.clear();
                break;
            case 2:
                transactionOutcomeListController.clear();
                break;
        }
    }
    
    public void search() {
        search(tab);
    }

    public void search(int tab) {
        this.tab = tab;
        switch (tab) {
            case 0:
                transactionAllListController.search();
                break;
            case 1:
                transactionIncomeListController.search();
                break;
            case 2:
                transactionOutcomeListController.search();
                break;
        }
    }

    public String getDate(Date date, String pattern) {
        return DateUtil.getFormattedDate(date, pattern);
    }

    public String getValue(BigDecimal value, String locale) {
        return CurrencyUtil.getStringValue(value, locale);
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/TransactionOutcomeListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.enumerated.TransactionType;
import br.com.mugi.repository.TransactionRepository;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author jose.bonifacio
 */
@Named
@SessionScoped
public class TransactionOutcomeListController extends ListControllerImpl implements Serializable {

    @Inject
    private TransactionRepository transactionRepository;

    @Override
    public void loadItems() {
        setItems(transactionRepository.getAllAsTransactionListDTO(Session.getUser(), TransactionType.OUTCOME,
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }
}

Mugi/src/main/java/br/com/mugi/controller/list/TransferListController.java
package br.com.mugi.controller.list;

import br.com.mugi.controller.util.Session;
import br.com.mugi.repository.TransferRepository;
import br.com.mugi.util.CurrencyUtil;
import br.com.mugi.util.DateUtil;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author BONIFACIO
 */
@Named
@SessionScoped
public class TransferListController extends ListControllerImpl implements Serializable {

    @Inject
    private TransferRepository transferRepository;

    @Override
    public void loadItems() {
        setItems(transferRepository.getAllAsTransferListDTO(Session.getUser(),
                getSearch(), this.getPage(), this.getMaxResultsPerPage()));
    }

    public String getDate(Date date, String pattern) {
        return DateUtil.getFormattedDate(date, pattern);
    }

    public String getValue(BigDecimal value, String locale) {
        return CurrencyUtil.getStringValue(value, locale);
    }
}

Mugi/src/main/webapp/secured/party/form.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:body>
        <ui:composition template="/template/form/layout.xhtml">

            <f:metadata>
                <f:viewParam name="id" value="#{partyFormController.party.id}" />
                <f:viewAction if="#{not empty param['id']}" action="#{partyFormController.loadParty(partyFormController.party.id)}" />
                <f:viewAction if="#{not empty param['id']}" action="#{partyMemberListController.setParty(partyFormController.party)}" />
                <f:viewAction if="#{empty param['id']}" action="#{partyMemberListController.newParty()}" />
                <f:viewAction action="#{partyMemberListController.search()}" />
            </f:metadata>

            <ui:param name="formBean" value="#{partyFormController}"/>
            <ui:param name="context" value="#{i18n['party.context.form']}" />
            <ui:param name="includeDelete" value="true"/>
            <ui:param name="deleteContext" value="#{i18n['party.delete.context']}"/>
            <ui:param name="entityName" value="#{partyFormController.party.name}"/>
            <ui:param name="entity" value="#{partyFormController.party}"/>
            <ui:param name="listController" value="#{partyMemberListController}" />
            <ui:param name="includeButtons" value="true" />
            <ui:param name="includeFooter" value="true" />
            <ui:param value="#{partyMemberListController.page}" name="page"/>
            <ui:param name="clickPath" value="$('.partyMemberModal').modal(); return false;"/>
            <ui:param name="update" value=":memberModalForm"/>
            <ui:param name="backToList" value="#{request.contextPath}/parties"/>

            <ui:define name="workArea" >
                <h:panelGroup>
                    <ui:decorate template="#{input}">
                        <ui:param name="label" value="#{i18n['party.input.name']}"/><ui:param name="for" value="name"/>
                        <ui:define name="field">
                            <b:inputText id="name" value="#{partyFormController.party.name}"></b:inputText>
                        </ui:define>
                    </ui:decorate>
                    
                    <ui:decorate template="#{input}">
                        <ui:param name="label" value="#{i18n['party.input.members']}"/>
                    </ui:decorate>

                </h:panelGroup> 

                <b:well>
                    <b:commandButton value="#{i18n['actions.new']}"
                                     icon="plus"
                                     ajax="true"
                                     actionListener="#{partyFormController.newPartyMember()}"
                                     update="#{update}"
                                     oncomplete="$('.partyMemberModal').modal();
                                     return false;"/>
                    <ui:decorate template="/template/list/table.xhtml">                    
                        <ui:define name="header">
                            <td style="width: 300px;"><h:outputLabel value="#{i18n['partyMember.list.memberNickname']}" /> </td>
                            <td style="width: 50px;" ><h:outputLabel value="#{i18n['partyMember.list.job']}" /> </td>
                        </ui:define>
                        <ui:define name="rows">
                            <ui:repeat value="#{partyMemberListController.items}" var="partyMember" >
                                <ui:param value="#{partyMember}" name="item"/>
                                <ui:decorate template="/template/list/viewableRow.xhtml" >
                                    <ui:define name="columns">
                                        <td style="width: 300px;">#{partyMember.memberNickname}</td>
                                        <td style="width: 50px;" >#{partyMember.job}</td>
                                    </ui:define>
                                </ui:decorate>
                            </ui:repeat> 
                        </ui:define>
                    </ui:decorate> 
                </b:well>
            </ui:define>
            <ui:define name="additionalModal">
                <ui:include src="partyMemberModal.xhtml" /> 
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Mugi/src/main/webapp/secured/party/formWithList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:body>
        <ui:composition template="/template/form/layout.xhtml">

            <f:metadata>
                <f:viewParam name="id" value="#{partyFormController.party.id}" />
                <f:viewAction if="#{not empty param['id']}" action="#{partyFormController.loadParty(partyFormController.party.id)}" />
            </f:metadata>

            <ui:param name="formBean" value="#{partyFormController}"/>
            <ui:param name="context" value="#{i18n['party.context']}" />
            <ui:param name="deleteContext" value="#{i18n['delete.context.party']}"/>
            <ui:param name="entityName" value="#{partyFormController.party.name}"/>
            <ui:param name="entity" value="#{partyFormController.party}"/>

            <ui:define name="workArea" >
                <h:panelGroup>
                    <h:outputText value="#{i18n['party.input.name']}"/>
                    <b:inputText value="#{partyFormController.party.name}"></b:inputText>
                </h:panelGroup> 

                <ui:param name="listController" value="#{memberListController}" />
                <ui:param name="includeButtons" value="true" />
                <ui:param name="includeFooter" value="true" />
                <ui:decorate template="/template/list/table.xhtml">
                    <ui:define name="header">
                        <td style="width: 50px;" class="visible-md visible-lg"><h:outputLabel value="#{i18n['member.list.id']}" /></td>
                        <td style="width: 300px;"><h:outputLabel value="#{i18n['member.list.nickname']}" /></td>
                        <td style="width: 600px;"><h:outputLabel value="#{i18n['member.list.name']}" /> </td>
                        <td style="width: 300px;" class="visible-md visible-lg"><h:outputLabel value="#{i18n['member.list.ropdAddress']}" /> </td>
                    </ui:define>
                    <ui:define name="rows">
                        <ui:repeat value="#{memberListController.items}" var="member" >
                            <ui:param value="#{member}" name="item"/>
                            <ui:param value="#{memberListController.page}" name="page"/>
                            <ui:decorate template="/template/list/row.xhtml" >
                                <ui:define name="columns">
                                    <td style="width: 50px;" class="visible-md visible-lg">#{member.id}</td>
                                    <td style="width: 300px;">#{member.nickname}</td>
                                    <td style="width: 600px;">#{member.name}</td>
                                    <td style="width: 300px;" class="visible-md visible-lg">#{member.ropdAddress}</td>
                                </ui:define>
                            </ui:decorate>
                        </ui:repeat> 
                    </ui:define>
                    <h:outputText class="text-center pull-right" value="#{listController.firstPageResult}-#{listController.lastPageResult} #{i18n['table.of']} #{listController.totalRows}"/>
                </ui:decorate> 
            </ui:define>     
        </ui:composition>
    </h:body>
</html>

Mugi/src/main/webapp/secured/party/list.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:body>
        <ui:composition template="/template/list/layout.xhtml">
            <f:metadata>
                <f:viewAction action="#{partyListController.clear()}" />
            </f:metadata>

            <ui:param name="listController" value="#{partyListController}" />
            <ui:param name="context" value="#{i18n['party.context.list']}" />
            <ui:param name="includeFooter" value="true"/>
            <ui:param value="#{partyListController.page}" name="page"/>

            <ui:define name="additionalContext">
                <b:label text="5 members not set" severity="warning"/>
            </ui:define>
            <ui:define name="workArea" >
                <ui:decorate template="/template/list/table.xhtml">
                    <ui:define name="header">
                        <td style="width: 50px;" class="visible-md visible-lg"><h:outputLabel value="#{i18n['party.list.id']}" /></td>
                        <td style="width: 600px;"><h:outputLabel value="#{i18n['party.list.name']}" /> </td>
                    </ui:define>
                    <b:label text="1" severity="info"/>
                    <ui:define name="rows">
                        <ui:repeat value="#{partyListController.items}" var="party" >
                            <ui:param value="#{party}" name="item"/>
                            <ui:param name="clickPath" value="document.location.href = '../party/#{item.id}'"/>
                            <ui:decorate template="/template/list/clickableRow.xhtml" >
                                <ui:define name="columns">
                                    <td style="width: 50px;" class="visible-md visible-lg">#{party.id}</td>
                                    <td style="width: 600px;">#{party.name}</td>
                                </ui:define>
                            </ui:decorate>
                        </ui:repeat> 
                    </ui:define>
                </ui:decorate>  
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Mugi/src/main/webapp/secured/party/partyMemberModal.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:body>
        <ui:composition> 
            <b:modal id="memberModal" title="#{i18n['party.memberModal.title']}" styleClass="partyMemberModal">
                <h:form id="memberModalForm">
                    <ui:decorate template="#{input}">
                        <ui:param name="label" value="#{i18n['party.partyMember.input.member']}"/><ui:param name="for" value="member"/>
                        <ui:define name="field">
                            <b:selectOneMenu id="member" value="#{partyFormController.partyMember.member}" >
                                <f:selectItems value="#{partyFormController.availableMembers}" var="member" itemLabel="#{member.nickname}" itemValue="#{member}"/>
                            </b:selectOneMenu>
                        </ui:define>
                    </ui:decorate>

                    <ui:decorate template="#{input}">
                        <ui:param name="label" value="#{i18n['party.partyMember.input.job']}"/><ui:param name="for" value="job"/>
                        <ui:define name="field">
                            <b:selectOneMenu id="job" value="#{partyFormController.partyMember.job}" >
                                <f:selectItems value="#{partyFormController.jobs}" var="job" itemLabel="#{job}" itemValue="#{job}"/>
                            </b:selectOneMenu>
                        </ui:define>
                    </ui:decorate>

                    <hr style="margin: -20px"/>
                    <div class="work-area-buttons">
                        <b:commandButton value="#{i18n['actions.save']}" look="primary" action="#{partyFormController.saveMember()}"/>
                        <b:button value="#{i18n['actions.cancel']}" dismiss="modal" onclick="return false;"/>
                        <b:commandButton value="#{i18n['actions.delete']}" look="danger" disabled="#{partyFormController.partyMember.new}" action="#{partyFormController.deleteMember()}"/>
                    </div>
                </h:form>
            </b:modal>
        </ui:composition>
    </h:body>
</html>